import { MigrationInterface, QueryRunner } from "typeorm";

export class Updatestaffentity1755001713591 implements MigrationInterface {
    name = 'Updatestaffentity1755001713591'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_556b47eef6c3c7758915d1bc05f"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_c3fe01125c99573751fe5e55666"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_a9753b9ee30a302f26f1e62ed73"`);
        await queryRunner.query(`CREATE TABLE "staffBranches" ("staffId" integer NOT NULL, "branchId" integer NOT NULL, CONSTRAINT "PK_fbd30403bfed0e27ad8419aa502" PRIMARY KEY ("staffId", "branchId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_da994170ec0917eb5f3f17c55a" ON "staffBranches" ("staffId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e5c4aa1b20eeac5a2dbe7fb81" ON "staffBranches" ("branchId") `);
        await queryRunner.query(`CREATE TABLE "staffPermissions" ("staffId" integer NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "PK_92fcb7092f6be68edd2ff668950" PRIMARY KEY ("staffId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08c92ebbb08811cdff73dbdb59" ON "staffPermissions" ("staffId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5bfda9131cfca149684218fc30" ON "staffPermissions" ("permissionId") `);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "certification_files"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "login_details"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "REL_a9753b9ee30a302f26f1e62ed7"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "address_id"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "access_level"`);
        await queryRunner.query(`DROP TYPE "public"."staff_access_level_enum"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "selected_branch"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "imported_table_2_2"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "team_namur_1"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "imported_table_2_3"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "team_namur_2"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "specialization_2"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "rosa_link"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "google_agenda_link"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "appointment_start"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "appointment_end"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "appointment_alert"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "specialization_1"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "registration_number"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "imported_table_2"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "field_27"`);
        await queryRunner.query(`CREATE TYPE "public"."staff_accesslevel_enum" AS ENUM('staff', 'branch-admin', 'super-admin')`);
       await queryRunner.query(`ALTER TABLE "staff" ADD "accessLevel" "public"."staff_accesslevel_enum"`);
await queryRunner.query(`UPDATE "staff" SET "accessLevel" = 'staff' WHERE "accessLevel" IS NULL`);
await queryRunner.query(`ALTER TABLE "staff" ALTER COLUMN "accessLevel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "registrationNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "certificationFiles" jsonb`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "loginDetails" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "createdBy" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "updatedBy" integer`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "specialization1" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "importedTable2" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "field27" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "importedTable22" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "teamNamur1" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "importedTable23" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "teamNamur2" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "specialization2" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "rosaLink" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "googleAgendaLink" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "appointmentStart" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "appointmentEnd" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "appointmentAlert" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "addressId" integer`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "UQ_ba7013cadf78e45f692ac29758d" UNIQUE ("addressId")`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "roleId" integer`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "selectedBranch" integer`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "preferences" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_ba7013cadf78e45f692ac29758d" FOREIGN KEY ("addressId") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_10288fdeaacf288bbd4d6469fef" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_fa9c2fc4231e872de1ad55d4eb1" FOREIGN KEY ("selectedBranch") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staffBranches" ADD CONSTRAINT "FK_da994170ec0917eb5f3f17c55ad" FOREIGN KEY ("staffId") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staffBranches" ADD CONSTRAINT "FK_6e5c4aa1b20eeac5a2dbe7fb813" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staffPermissions" ADD CONSTRAINT "FK_08c92ebbb08811cdff73dbdb594" FOREIGN KEY ("staffId") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staffPermissions" ADD CONSTRAINT "FK_5bfda9131cfca149684218fc304" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "staffPermissions" DROP CONSTRAINT "FK_5bfda9131cfca149684218fc304"`);
        await queryRunner.query(`ALTER TABLE "staffPermissions" DROP CONSTRAINT "FK_08c92ebbb08811cdff73dbdb594"`);
        await queryRunner.query(`ALTER TABLE "staffBranches" DROP CONSTRAINT "FK_6e5c4aa1b20eeac5a2dbe7fb813"`);
        await queryRunner.query(`ALTER TABLE "staffBranches" DROP CONSTRAINT "FK_da994170ec0917eb5f3f17c55ad"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_fa9c2fc4231e872de1ad55d4eb1"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_10288fdeaacf288bbd4d6469fef"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_ba7013cadf78e45f692ac29758d"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "preferences" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "selectedBranch"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "roleId"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "UQ_ba7013cadf78e45f692ac29758d"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "addressId"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "appointmentAlert"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "appointmentEnd"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "appointmentStart"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "googleAgendaLink"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "rosaLink"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "specialization2"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "teamNamur2"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "importedTable23"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "teamNamur1"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "importedTable22"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "field27"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "importedTable2"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "specialization1"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "loginDetails"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "certificationFiles"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "registrationNumber"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "accessLevel"`);
        await queryRunner.query(`DROP TYPE "public"."staff_accesslevel_enum"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "field_27" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "imported_table_2" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "registration_number" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "specialization_1" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "appointment_alert" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "appointment_end" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "appointment_start" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "google_agenda_link" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "rosa_link" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "specialization_2" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "team_namur_2" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "imported_table_2_3" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "team_namur_1" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "imported_table_2_2" character varying`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "updated_by" integer`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "created_by" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "selected_branch" integer`);
        await queryRunner.query(`CREATE TYPE "public"."staff_access_level_enum" AS ENUM('staff', 'branch-admin', 'super-admin')`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "accessLevel" "public"."staff_accesslevel_enum"`);
await queryRunner.query(`UPDATE "staff" SET "accessLevel" = 'staff' WHERE "accessLevel" IS NULL`);
await queryRunner.query(`ALTER TABLE "staff" ALTER COLUMN "accessLevel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "role_id" integer`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "address_id" integer`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "REL_a9753b9ee30a302f26f1e62ed7" UNIQUE ("address_id")`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "login_details" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "certification_files" jsonb`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bfda9131cfca149684218fc30"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08c92ebbb08811cdff73dbdb59"`);
        await queryRunner.query(`DROP TABLE "staffPermissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e5c4aa1b20eeac5a2dbe7fb81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da994170ec0917eb5f3f17c55a"`);
        await queryRunner.query(`DROP TABLE "staffBranches"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_a9753b9ee30a302f26f1e62ed73" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_c3fe01125c99573751fe5e55666" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_556b47eef6c3c7758915d1bc05f" FOREIGN KEY ("selected_branch") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);

    }

}
