version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: node dist/src/main
    restart: always
    networks:
      - app_network
    environment:
      DATABASE_HOST: postgres_db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: re_ai@2025

  postgres_db:
    image: postgres:16
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: re_ai@2025
    networks:
      - app_network

volumes:
  postgres_db_data:
    driver: local
    labels:
      - "io.vendure.create.name=my-shop"

networks:
  app_network:
    driver: bridge