name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Sets up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t re-ai-be-api:latest .

      - name: Tag Docker image
        run: |
          docker tag re-ai-be-api ${{ secrets.DOCKER_USERNAME }}/re_ai_be:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/re_ai_be:latest

      - name: Deploy to the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} '
              if ! command -v docker &> /dev/null; then
                  echo "Docker is not installed. Installing Docker..."
                  
                  sudo apt-get update -y && \
                  sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
                  
                  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

                  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                  
                  sudo apt-get update -y && \
                  sudo apt-get install -y docker-ce docker-ce-cli containerd.io
                  
                  docker --version || { echo "Docker installation failed"; exit 1; }
              else
                  echo "Docker is already installed."
              fi
    
              docker pull ${{ secrets.DOCKER_USERNAME }}/re_ai_be:latest && \
              
              (docker stop re_ai_be || true) && \
              (docker rm re_ai_be || true) && \
              
              docker image prune -a -f && \
              
              docker run -d --name re_ai_be -p 3500:3500 ${{ secrets.DOCKER_USERNAME }}/re_ai_be:latest
          '

